@startuml

    together {

        class Usuario {
        -String nome
        -String email
        -String senha
        +realizarLogin(): void
        +consultarExtratoConta(): void
    }

        class Aluno {
            -String cpf
            -String rg
            -String endereco
            -String instituicao
            -String curso
            +cadastrar(): void
            +receberMoedas(montante: int, motivo: String): void
            +trocarMoedas(vantagem: Vantagem): void
        }

        class Professor {
            -String cpf
            -String departamento
            -int saldoMoedas = 1000
            +enviarMoedas(aluno: Aluno, montante: int, motivo: String): void
            +adicionarMoedas(saldoMoedas: int): void
        }

        class Empresa {
            -String cnpj
            +cadastrarVantagem(vantagem: Vantagem): void
        }
    }

    class Vantagem {
        -String descricao
        -String foto
        -int valor
        +gerarCodigoResgate(): String
    }
    
    class Transacao {
        -String tipo
        -int montante
        -Date data
    }

    class Extrato {
    +consultarTransacoes(): List<Transacao>
    }

    class Notificacao {
        -String mensagem
        +enviarNotificacao(destinatario: Usuario): void
    }

    class Email {
        -String remetente
        -String destinatario
        -String assunto
        -String corpo
        +enviar(): void
    }
    
    Empresa ---|> Usuario 
    Professor ---|> Usuario 
    Aluno ---|> Usuario


    Email --> Vantagem 
    Aluno --> Extrato 
    Aluno --> Vantagem 
    Aluno --> Notificacao 
    Aluno --> Email 
    Professor --> Extrato 
    Professor --> Notificacao 
    Professor --> Aluno 
    Empresa <--> Vantagem 
    Vantagem --> Email 
    Extrato --> Transacao 
    Transacao --> Usuario 

@enduml
